# Notification for SSL expirations and renewl. Should automatically renew, but just in case.
  - alias: 'SSL expiration notification'
    trigger:
      platform: numeric_state
      entity_id: sensor.ssl_cert_expiration
      below: 21
    action:
      service: notify.slack
      data:
        message: 'Warning - SSL certificate expires in 21 days and has not been automatically renewed'

# Send a slack message: If any security sensor changes state (doesn't matter which way on/off)
#                       AND no one is currently home
  - alias: 'Alarm Notification'
    trigger:
      platform: state
      entity_id:
        - binary_sensor.front_door
        - binary_sensor.garage_door
        - binary_sensor.patio_door
        - binary_sensor.basement_windows
        - binary_sensor.bathroom_window
        - binary_sensor.living_room_window_1
        - binary_sensor.living_room_window_2
        - binary_sensor.living_room_window_3
        - binary_sensor.mudroom_window
        - binary_sensor.dining_window_1
        - binary_sensor.dining_window_2
        - binary_sensor.study_windows
    condition:
      condition: state
      entity_id: 'group.all_devices'
      state: 'not_home'
    action:
      service: notify.slack
      data:
        message: 'SECURITY ALERT - A sensor changed state while no one is home'
