homeassistant:
  auth_providers:
   - type: homeassistant
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: US/Mountain
  # Customization file
  customize: !include customize.yaml

# Enable the authorization component
auth:

konnected: !include konnected.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
        #  extra_html_url:
        #- /local/custom_ui/state-card-floorplan.html

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: !secret ssl_cert
  ssl_key: !secret ssl_key
  base_url: !secret base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Log files
logger:
  default: info

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
weather:
  - platform: darksky
    api_key: !secret darksky_api_key

device_tracker: !include device_trackers.yaml

# Remote access
duckdns:
  domain: !secret dns_domain
  access_token: !secret dns_token

# Text to speech
tts:
  - platform: google

# Cloud
#cloud:

# Security panel
panel_custom: !include panel_custom.yaml
#binary_sensor: !include binary_sensors.yaml

sensor: !include sensors.yaml
notify: !include notify.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
